import { getAllPosts } from '#lib/posts-related-api';
import { IPost } from '#type/post';
import fs from 'fs';

const getPostPriority = () => {
  // TODO : 최근에 가까운 글일 수록 우선순위가 높다.

  return '1';
};

const makeSiteMapItemXml = (url: string, priority: string) => {
  const now = new Date().toISOString();
  return `<url>
        <loc>${url}</loc> // 사이트맵 주소
        <lastmod>${now}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>${priority}</priority>
    </url>`;
};

const wrapSiteMap = (body: string[]) => {
  return `<?xml version="1.0" encoding="utf-8"?>
    <!--Generated by Screaming Frog SEO Spider 9.4-->
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        ${body}
    </urlset>`;
};

(async () => {
  // 게시글 정보들을 가져옵니다.
  const posts = await getAllPosts();
  const post_priority = getPostPriority();
  // 해당 정보를 기준으로 사이트맵 형식으로 convert 해주도록 합니다.
  const newPostsSiteMap = posts.map((post: IPost) =>
    makeSiteMapItemXml(` /blog/${post.slug}`, post_priority),
  );

  // 최종적으로 xml 형식으로 wrap 시켜주도록 합니다.
  const finalSitemap = wrapSiteMap(newPostsSiteMap);
  fs.writeFileSync('../public/sitemap-posts.xml', finalSitemap, 'utf8');
})();
